// Builds the static preview deployment into build/.
//
// The preview has no server: the transpiled ABAP application is bundled into a
// service worker, and the browser assets and the database schema - which the
// local server reads from disk at startup - are compiled into that bundle.
// This script generates those two modules, runs webpack and copies the page
// that installs the worker.
import {copyFile, mkdir, readFile, writeFile} from "node:fs/promises";
import {createRequire} from "node:module";
import {resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {sqliteSchemaStatements} from "./local-database.mjs";
import {readSerializedAssets} from "./local-assets.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const generated = resolve(root, "web/generated");
const build = resolve(root, "build");

function module(description, name, value) {
  return `// Generated by scripts/build-preview.mjs. Do not edit.\n`
    + `//\n`
    + `${description}\n`
    + `export const ${name} = ${JSON.stringify(value, undefined, 2)};\n`;
}

await mkdir(generated, {recursive: true});

const runtime = await readFile(resolve(root, "output/init.mjs"), "utf8");
await writeFile(resolve(generated, "sqlite-schema.mjs"), module(
  "// The CREATE TABLE statements read out of the generated runtime, so the\n"
  + "// preview creates the same tables the local server does.",
  "sqliteSchema",
  sqliteSchemaStatements(runtime),
), "utf8");

const assets = await readSerializedAssets(resolve(root, "src/frontend"));
await writeFile(resolve(generated, "frontend-assets.mjs"), module(
  "// The serialized SMIM assets, which an installed service reads from the\n"
  + "// MIME repository and the preview hands to the local asset store.",
  "frontendAssets",
  assets,
), "utf8");

console.log(`Generated the schema and ${assets.length} browser assets`);

const require = createRequire(import.meta.url);
const webpack = require("webpack");
const configuration = require(resolve(root, "webpack.config.cjs"));

const statistics = await new Promise((fulfil, reject) => {
  webpack(configuration, (error, result) => {
    if (error) {
      reject(error);
      return;
    }
    if (result.hasErrors()) {
      reject(new Error(result.toString({colors: false, errorDetails: true})));
      return;
    }
    fulfil(result);
  });
});
console.log(statistics.toString({colors: false, preset: "minimal"}));

// The bundle answers every request below the preview directory, but something
// has to install it first. index.html is that page, and is only ever shown
// before the worker exists.
await mkdir(build, {recursive: true});
await copyFile(resolve(root, "web/index.html"), resolve(build, "index.html"));
console.log(`Wrote ${resolve(build, "index.html")}`);
console.log(`Preview build is in ${build}`);
